// Danh sách ngân hàng chuẩn theo mã BIN NAPAS / VietQR kèm logo icon
export const BANK_LIST = [
  { code: 'vcb', bin: '970436', name: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank - VCB)', logo: 'https://api.vietqr.io/img/VCB.png' },
  { code: 'tcb', bin: '970407', name: 'Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank - TCB)', logo: 'https://api.vietqr.io/img/TCB.png' },
  { code: 'mbbank', bin: '970422', name: 'Ngân hàng TMCP Quân Đội (MB Bank - MB)', logo: 'https://api.vietqr.io/img/MB.png' },
  { code: 'bidv', bin: '970418', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)', logo: 'https://api.vietqr.io/img/BIDV.png' },
  { code: 'vietinbank', bin: '970415', name: 'Ngân hàng TMCP Công Thương Việt Nam (VietinBank - ICB)', logo: 'https://api.vietqr.io/img/ICB.png' },
  { code: 'acb', bin: '970416', name: 'Ngân hàng TMCP Á Châu (ACB)', logo: 'https://api.vietqr.io/img/ACB.png' },
  { code: 'vpbank', bin: '970432', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)', logo: 'https://api.vietqr.io/img/VPB.png' },
  { code: 'tpbank', bin: '970423', name: 'Ngân hàng TMCP Tiên Phong (TPBank)', logo: 'https://api.vietqr.io/img/TPB.png' },
  { code: 'sacombank', bin: '970403', name: 'Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank - STB)', logo: 'https://api.vietqr.io/img/STB.png' },
  { code: 'hdbank', bin: '970444', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh (HDBank)', logo: 'https://api.vietqr.io/img/HDB.png' },
  { code: 'msb', bin: '970405', name: 'Ngân hàng TMCP Hàng Hải Việt Nam (MSB)', logo: 'https://api.vietqr.io/img/MSB.png' },
  { code: 'shb', bin: '970431', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)', logo: 'https://api.vietqr.io/img/SHB.png' },
  { code: 'shinhan', bin: '970424', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam (Shinhan Bank)', logo: 'https://api.vietqr.io/img/SHINHAN.png' },
  { code: 'vietcapital', bin: '970454', name: 'Ngân hàng TMCP Bản Việt (VietCapitalBank)', logo: 'https://api.vietqr.io/img/BVB.png' },
  { code: 'vib', bin: '970441', name: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)', logo: 'https://api.vietqr.io/img/VIB.png' },
  { code: 'vietbank', bin: '970433', name: 'Ngân hàng TMCP Việt Nam Thương Tín (VietBank)', logo: 'https://api.vietqr.io/img/VB.png' },
  { code: 'scb', bin: '970443', name: 'Ngân hàng TMCP Sài Gòn (SCB)', logo: 'https://api.vietqr.io/img/SCB.png' },
  { code: 'ocb', bin: '970409', name: 'Ngân hàng TMCP Phương Đông (OCB)', logo: 'https://api.vietqr.io/img/OCB.png' },
  { code: 'abbank', bin: '970425', name: 'Ngân hàng TMCP An Bình (ABBank)', logo: 'https://api.vietqr.io/img/ABB.png' },
  { code: 'donga', bin: '970434', name: 'Ngân hàng TMCP Đông Á (DongA Bank)', logo: 'https://api.vietqr.io/img/DOB.png' },
  { code: 'saigonbank', bin: '970400', name: 'Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)', logo: 'https://api.vietqr.io/img/SGICB.png' },
  { code: 'pvcombank', bin: '970412', name: 'Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)', logo: 'https://api.vietqr.io/img/PVCB.png' },
  { code: 'namabank', bin: '970419', name: 'Ngân hàng TMCP Nam Á (Nam A Bank)', logo: 'https://api.vietqr.io/img/NAB.png' },
  { code: 'ncb', bin: '970426', name: 'Ngân hàng TMCP Quốc Dân (NCB)', logo: 'https://api.vietqr.io/img/NCB.png' },
  { code: 'vietabank', bin: '970427', name: 'Ngân hàng TMCP Việt Á (VietABank)', logo: 'https://api.vietqr.io/img/VAB.png' },
  { code: 'pgbank', bin: '970430', name: 'Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)', logo: 'https://api.vietqr.io/img/PGB.png' },
  { code: 'baovietbank', bin: '970438', name: 'Ngân hàng TMCP Bảo Việt (BaoVietBank)', logo: 'https://api.vietqr.io/img/BVBV.png' },
  { code: 'lpbank', bin: '970449', name: 'Ngân hàng Bưu điện Liên Việt (LPBank)', logo: 'https://api.vietqr.io/img/LPB.png' },
  { code: 'kienlongbank', bin: '970452', name: 'Ngân hàng TMCP Kiên Long (KienlongBank)', logo: 'https://api.vietqr.io/img/KLB.png' },
  { code: 'cimb', bin: '422589', name: 'CIMB Bank Việt Nam', logo: 'https://api.vietqr.io/img/CIMB.png' },
  { code: 'hsbc', bin: '458761', name: 'HSBC Việt Nam', logo: 'https://api.vietqr.io/img/HSBC.png' }
];