// Danh sách ngân hàng chuẩn theo mã BIN NAPAS / VietQR để gọi API tra cứu
export const BANK_LIST = [
  { code: 'vcb', bin: '970436', name: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank - VCB)' },
  { code: 'tcb', bin: '970407', name: 'Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank - TCB)' },
  { code: 'mbbank', bin: '970422', name: 'Ngân hàng TMCP Quân Đội (MB Bank - MB)' },
  { code: 'bidv', bin: '970418', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)' },
  { code: 'vietinbank', bin: '970415', name: 'Ngân hàng TMCP Công Thương Việt Nam (VietinBank - ICB)' },
  { code: 'acb', bin: '970416', name: 'Ngân hàng TMCP Á Châu (ACB)' },
  { code: 'vpbank', bin: '970432', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)' },
  { code: 'tpbank', bin: '970423', name: 'Ngân hàng TMCP Tiên Phong (TPBank)' },
  { code: 'sacombank', bin: '970403', name: 'Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank - STB)' },
  { code: 'hdbank', bin: '970444', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh (HDBank)' },
  { code: 'msb', bin: '970405', name: 'Ngân hàng TMCP Hàng Hải Việt Nam (MSB)' },
  { code: 'shb', bin: '970431', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)' },
  { code: 'shinhan', bin: '970424', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam (Shinhan Bank)' },
  { code: 'vietcapital', bin: '970454', name: 'Ngân hàng TMCP Bản Việt (VietCapitalBank)' },
  { code: 'vib', bin: '970441', name: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)' },
  { code: 'vietbank', bin: '970433', name: 'Ngân hàng TMCP Việt Nam Thương Tín (VietBank)' },
  { code: 'scb', bin: '970443', name: 'Ngân hàng TMCP Sài Gòn (SCB)' },
  { code: 'ocb', bin: '970409', name: 'Ngân hàng TMCP Phương Đông (OCB)' },
  { code: 'abbank', bin: '970425', name: 'Ngân hàng TMCP An Bình (ABBank)' },
  { code: 'donga', bin: '970434', name: 'Ngân hàng TMCP Đông Á (DongA Bank)' },
  { code: 'saigonbank', bin: '970400', name: 'Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)' },
  { code: 'pvcombank', bin: '970412', name: 'Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)' },
  { code: 'namabank', bin: '970419', name: 'Ngân hàng TMCP Nam Á (Nam A Bank)' },
  { code: 'ncb', bin: '970426', name: 'Ngân hàng TMCP Quốc Dân (NCB)' },
  { code: 'vietabank', bin: '970427', name: 'Ngân hàng TMCP Việt Á (VietABank)' },
  { code: 'pgbank', bin: '970430', name: 'Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)' },
  { code: 'baovietbank', bin: '970438', name: 'Ngân hàng TMCP Bảo Việt (BaoVietBank)' },
  { code: 'lpbank', bin: '970449', name: 'Ngân hàng Bưu điện Liên Việt (LPBank)' },
  { code: 'kienlongbank', bin: '970452', name: 'Ngân hàng TMCP Kiên Long (KienlongBank)' },
  { code: 'cimb', bin: '422589', name: 'CIMB Bank Việt Nam' },
  { code: 'hsbc', bin: '458761', name: 'HSBC Việt Nam' }
];